#
#  $Id: Makefile 1.1 2008/06/25 14:25:52CST Daron Chabot (chabotd) Exp  $
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc

include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/directory.cfg

SUBDIRS=libics110bl libvmic2536 utils mainApp test

